### First sight at raw data
#### This file has been developed simultaneously with extract.py and transform.py

In [2]:
# Importing modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import sys

In [ ]:
sys.path.append(str(Path.cwd().parent))
from backend.config.settings import PATHS

In [15]:
water_path = PATHS['raw_data'] / 'water.csv'
water_pd = pd.read_csv(water_path)
water_pd.head()

             DATE  CURRENT_WATER  ID
0  04/09/12 00:00           56.0  18
1  23/10/12 00:00           50.0  18
2  27/11/12 00:00           55.0  18
3  22/01/91 00:00           53.0  18
4  21/05/91 00:00           52.0  18

In [16]:
reservoirs_path = PATHS['raw_data'] / 'reservoirs.csv'
reservoirs_pd = pd.read_csv(reservoirs_path)
reservoirs_pd.head()

,ID,SCOPE_NAME,RESERVOIR_NAME,TOTAL_WATER,ELECTRIC_FLAG
0,1,GUADALQUIVIR,"BREÑA, LA",103.0,0
1,3,GUADALQUIVIR,"FERNANDINA, LA",247.0,0
2,5,GUADALQUIVIR,PUEBLA DE CAZALLA,87.0,0
3,6,GUADALQUIVIR,PEDRO MARÍN,19.0,0
4,9,CUENCA MEDITERRÁNEA ANDALUZA,"VIÑUELA, LA",170.0,0

In [17]:
detailed_path = PATHS['raw_data'] / 'UTF8list-3.tsv'
detailed_reservoirs_pd = pd.read_csv(detailed_path, sep='\t')
detailed_reservoirs_pd.head()

,CODE,NAME,RESERVOIR,X,Y,BASIN,RIVERBED,GOOGLE,OPENSTREETMAP,WIKIDATA,PROVINCE,AUTONOMOUS_COMMUNITY,TYPE,CREST_ELEVATION,DAM_HEIGHT,REPORT
0,9250031,SALLENTE,SALLENTE,"42,5003709690001","0,991459934000034",EBRO,BARRANC DE LA LORA,NaN,NaN,NaN,Lleida,Cataluña,Presa de materiales sueltos de pantalla asfáltica,1770,89,https://sig.mapama.gob.es/WebServices/clientew...
1,3450047,CAZALEGAS,Cazalegas Dam,"40,01298709","-4,70624804799996",TAJO,RÍO ALBERCHE,https://www.google.com/search?kgmid=/g/11dfr4j268,NaN,https://www.wikidata.org/wiki/Q30278314,Toledo,Castilla - La Mancha,Presa de materiales sueltos de pantalla de hor...,NaN,NaN,https://sig.mapama.gob.es/WebServices/clientew...
2,9250014,LAGO NEGRO,LAGO NEGRO,"42,5422861970001","1,04058219400002",EBRO,NaN,NaN,NaN,NaN,Lleida,Cataluña,Presa de materiales sueltos zonificada o de nú...,2340,11,https://sig.mapama.gob.es/WebServices/clientew...
3,9500034,"TORCAS, LAS",Las Trocas reservoir,"41,294686266","-1,08744698599997",EBRO,RÍO HUERVA,NaN,NaN,https://www.wikidata.org/wiki/Q23991169,Zaragoza,Aragón,Presa de fábrica de gravedad (hormigón vibrado),"624,799999999999","39,45",https://sig.mapama.gob.es/WebServices/clientew...
4,3190006,"BUJEDA, LA","BUJEDA, LA","40,244500658","-2,83518801499997",TAJO,SIN NOMBRE,NaN,NaN,NaN,Guadalajara,Castilla - La Mancha,Presa de materiales sueltos homogénea,"905,5","39,5",https://sig.mapama.gob.es/WebServices/clientew...

In [12]:
# First we will make sure that every data is in the correct format
# We start with water dataFrame
water_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683447 entries, 0 to 683446
Data columns (total 3 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   DATE           683447 non-null  object
 1   CURRENT_WATER  683445 non-null  float64
 2   ID             683447 non-null  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 15.6+ MB

In [13]:
reservoirs_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401 entries, 0 to 400
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              401 non-null    int64
 1   SCOPE_NAME      401 non-null    object
 2   RESERVOIR_NAME  401 non-null    object
 3   TOTAL_WATER     400 non-null    float64
 4   ELECTRIC_FLAG   401 non-null    int64
dtypes: float64(1), int64(2), object(2)
memory usage: 15.8+ KB

In [14]:
detailed_reservoirs_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CODE                  367 non-null    int64
 1   NAME                  367 non-null    object
 2   RESERVOIR             367 non-null    object
 3   X                     367 non-null    object
 4   Y                     367 non-null    object
 5   BASIN                 367 non-null    object
 6   RIVERBED              359 non-null    object
 7   GOOGLE                115 non-null    object
 8   OPENSTREETMAP         36 non-null     object
 9   WIKIDATA              187 non-null    object
 10  PROVINCE              367 non-null    object
 11  AUTONOMOUS_COMMUNITY  367 non-null    object
 12  TYPE                  367 non-null    object
 13  CREST_ELEVATION       184 non-null    object
 14  DAM_HEIGHT            184 non-null    object
 15  REPORT                367 non-null    object
dtypes: int64(1), object(15)
memory usage: 46.0+ KB